/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { AccountPropertyDTO } from './accountPropertyDTO';

export class AccountPropertiesDTO {
    /**
    * The address of the account in hexadecimal.
    */
    'address': string;
    'properties': Array<AccountPropertyDTO>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "Array<AccountPropertyDTO>"
        }    ];

    static getAttributeTypeMap() {
        return AccountPropertiesDTO.attributeTypeMap;
    }
}

