/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { LinkActionEnum } from './linkActionEnum';

export class AccountLinkTransactionBodyDTO {
    /**
    * The public key of the remote account.
    */
    'remoteAccountKey': string;
    'action': LinkActionEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "remoteAccountKey",
            "baseName": "remoteAccountKey",
            "type": "string"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "LinkActionEnum"
        }    ];

    static getAttributeTypeMap() {
        return AccountLinkTransactionBodyDTO.attributeTypeMap;
    }
}

