/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { SdaOfferInfoDTO } from './sdaOfferInfoDTO';

export class AccountSdaExchangeDTO {
    /**
    * The public key (accountId) of the owner.
    */
    'owner': string;
    /**
    * The address of the owner.
    */
    'ownerAddress': string;
    'version': number;
    'sdaOfferBalances': Array<SdaOfferInfoDTO>;
    'expiredSdaOfferBalances': Array<SdaOfferInfoDTO>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "owner",
            "baseName": "owner",
            "type": "string"
        },
        {
            "name": "ownerAddress",
            "baseName": "ownerAddress",
            "type": "string"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "number"
        },
        {
            "name": "sdaOfferBalances",
            "baseName": "sdaOfferBalances",
            "type": "Array<SdaOfferInfoDTO>"
        },
        {
            "name": "expiredSdaOfferBalances",
            "baseName": "expiredSdaOfferBalances",
            "type": "Array<SdaOfferInfoDTO>"
        }    ];

    static getAttributeTypeMap() {
        return AccountSdaExchangeDTO.attributeTypeMap;
    }
}

