/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { ArtifactExpiryReceiptDTOAllOf } from './artifactExpiryReceiptDTOAllOf';
import { ReceiptDTO } from './receiptDTO';
import { ReceiptTypeEnum } from './receiptTypeEnum';

/**
* An artifact namespace or mosaic expired.
*/
export class ArtifactExpiryReceiptDTO {
    /**
    * The version of the receipt.
    */
    'version': number;
    'type': ReceiptTypeEnum;
    'artifactId': Array<number>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ReceiptTypeEnum"
        },
        {
            "name": "artifactId",
            "baseName": "artifactId",
            "type": "Array<number>"
        }    ];

    static getAttributeTypeMap() {
        return ArtifactExpiryReceiptDTO.attributeTypeMap;
    }
}

