/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { PaymentsDTO } from './paymentsDTO';

export class BillingHistoryDTO {
    'start': Array<number>;
    'end': Array<number>;
    'payments': Array<PaymentsDTO>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "start",
            "baseName": "start",
            "type": "Array<number>"
        },
        {
            "name": "end",
            "baseName": "end",
            "type": "Array<number>"
        },
        {
            "name": "payments",
            "baseName": "payments",
            "type": "Array<PaymentsDTO>"
        }    ];

    static getAttributeTypeMap() {
        return BillingHistoryDTO.attributeTypeMap;
    }
}

