/*
 * Copyright 2023 ProximaX
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Sirius REST API Reference
 * https://bcdocs.xpxsirius.io/docs/rest-api/rest-api-overview/)
 */

import { RequestFile } from '../api';

export class Cosignature {
    /**
    * The hash of parent aggregate transaction that has been signed by a cosignatory of the transaction.
    */
    'parentHash'?: string;
    /**
    * The signatures generated by signing the parent aggregate transaction hash.
    */
    'signature'?: string;
    /**
    * The derivation scheme
    */
    'scheme'?: string;
    /**
    * The signer of the transaction.
    */
    'signer'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "parentHash",
            "baseName": "parentHash",
            "type": "string"
        },
        {
            "name": "signature",
            "baseName": "signature",
            "type": "string"
        },
        {
            "name": "scheme",
            "baseName": "scheme",
            "type": "string"
        },
        {
            "name": "signer",
            "baseName": "signer",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Cosignature.attributeTypeMap;
    }
}

