/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { EmbeddedAccountLinkTransactionDTO } from './embeddedAccountLinkTransactionDTO';
import { EmbeddedAccountPropertiesTransactionDTO } from './embeddedAccountPropertiesTransactionDTO';
import { EmbeddedAddressAliasTransactionDTO } from './embeddedAddressAliasTransactionDTO';
import { EmbeddedAddressMetadataTransactionDTO } from './embeddedAddressMetadataTransactionDTO';
import { EmbeddedBlockchainUpgradeTransactionDTO } from './embeddedBlockchainUpgradeTransactionDTO';
import { EmbeddedHashLockTransactionDTO } from './embeddedHashLockTransactionDTO';
import { EmbeddedModifyMultisigAccountTransactionDTO } from './embeddedModifyMultisigAccountTransactionDTO';
import { EmbeddedMosaicAliasTransactionDTO } from './embeddedMosaicAliasTransactionDTO';
import { EmbeddedMosaicDefinitionTransactionDTO } from './embeddedMosaicDefinitionTransactionDTO';
import { EmbeddedMosaicMetadataTransactionDTO } from './embeddedMosaicMetadataTransactionDTO';
import { EmbeddedMosaicSupplyChangeTransactionDTO } from './embeddedMosaicSupplyChangeTransactionDTO';
import { EmbeddedNamespaceMetadataTransactionDTO } from './embeddedNamespaceMetadataTransactionDTO';
import { EmbeddedNetworkConfigTransactionDTO } from './embeddedNetworkConfigTransactionDTO';
import { EmbeddedRegisterNamespaceTransactionDTO } from './embeddedRegisterNamespaceTransactionDTO';
import { EmbeddedSecretLockTransactionDTO } from './embeddedSecretLockTransactionDTO';
import { EmbeddedSecretProofTransactionDTO } from './embeddedSecretProofTransactionDTO';
import { EmbeddedTransactionMetaDTO } from './embeddedTransactionMetaDTO';
import { EmbeddedTransferTransactionDTO } from './embeddedTransferTransactionDTO';

export class EmbeddedTransactionInfoDTO {
    'meta': EmbeddedTransactionMetaDTO;
    'transaction': EmbeddedBlockchainUpgradeTransactionDTO | EmbeddedNetworkConfigTransactionDTO | EmbeddedAddressMetadataTransactionDTO | EmbeddedMosaicMetadataTransactionDTO | EmbeddedNamespaceMetadataTransactionDTO | EmbeddedMosaicDefinitionTransactionDTO | EmbeddedMosaicSupplyChangeTransactionDTO | EmbeddedRegisterNamespaceTransactionDTO | EmbeddedAddressAliasTransactionDTO | EmbeddedMosaicAliasTransactionDTO | EmbeddedTransferTransactionDTO | EmbeddedModifyMultisigAccountTransactionDTO | EmbeddedHashLockTransactionDTO | EmbeddedAccountPropertiesTransactionDTO | EmbeddedSecretLockTransactionDTO | EmbeddedSecretProofTransactionDTO | EmbeddedAccountLinkTransactionDTO;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "meta",
            "baseName": "meta",
            "type": "EmbeddedTransactionMetaDTO"
        },
        {
            "name": "transaction",
            "baseName": "transaction",
            "type": "EmbeddedBlockchainUpgradeTransactionDTO | EmbeddedNetworkConfigTransactionDTO | EmbeddedAddressMetadataTransactionDTO | EmbeddedMosaicMetadataTransactionDTO | EmbeddedNamespaceMetadataTransactionDTO | EmbeddedMosaicDefinitionTransactionDTO | EmbeddedMosaicSupplyChangeTransactionDTO | EmbeddedRegisterNamespaceTransactionDTO | EmbeddedAddressAliasTransactionDTO | EmbeddedMosaicAliasTransactionDTO | EmbeddedTransferTransactionDTO | EmbeddedModifyMultisigAccountTransactionDTO | EmbeddedHashLockTransactionDTO | EmbeddedAccountPropertiesTransactionDTO | EmbeddedSecretLockTransactionDTO | EmbeddedSecretProofTransactionDTO | EmbeddedAccountLinkTransactionDTO"
        }    ];

    static getAttributeTypeMap() {
        return EmbeddedTransactionInfoDTO.attributeTypeMap;
    }
}

