/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { EntityTypeEnum } from './entityTypeEnum';
import { ExchangeOfferTransactionBodyDTO } from './exchangeOfferTransactionBodyDTO';
import { TransactionDTO } from './transactionDTO';

export class ExchangeOfferTransactionDTO extends TransactionDTO {
    'offers': Array<ExchangeOfferTransactionBodyDTO>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "offers",
            "baseName": "offers",
            "type": "Array<ExchangeOfferTransactionBodyDTO>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(ExchangeOfferTransactionDTO.attributeTypeMap);
    }
}

