/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { HashLockInfoDTO } from './hashLockInfoDTO';
import { MetaLockDTO } from './metaLockDTO';

export class HashLockWithMeta {
    'meta': MetaLockDTO;
    'lock': HashLockInfoDTO;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "meta",
            "baseName": "meta",
            "type": "MetaLockDTO"
        },
        {
            "name": "lock",
            "baseName": "lock",
            "type": "HashLockInfoDTO"
        }    ];

    static getAttributeTypeMap() {
        return HashLockWithMeta.attributeTypeMap;
    }
}

