/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* The type of the metadata modification: * 0 - Add metadata. * 1 - Remove metadata. 
*/
export enum MetadataModificationTypeEnum {
    NUMBER_0 = <any> 0,
    NUMBER_1 = <any> 1
}
