/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { MosaicPropertyDTO } from './mosaicPropertyDTO';

export class MosaicDefinitionTransactionBodyDTO {
    /**
    * Random nonce used to generate the mosaic id.
    */
    'mosaicNonce': number;
    'mosaicId': Array<number>;
    'properties': Array<MosaicPropertyDTO>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mosaicNonce",
            "baseName": "mosaicNonce",
            "type": "number"
        },
        {
            "name": "mosaicId",
            "baseName": "mosaicId",
            "type": "Array<number>"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "Array<MosaicPropertyDTO>"
        }    ];

    static getAttributeTypeMap() {
        return MosaicDefinitionTransactionBodyDTO.attributeTypeMap;
    }
}

