/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class NetworkConfigBodyDTO {
    'applyHeightDelta': Array<number>;
    /**
    * Network config like a raw text.
    */
    'networkConfig': string;
    /**
    * Allowed versions of transaction in json format.
    */
    'supportedEntityVersions': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "applyHeightDelta",
            "baseName": "applyHeightDelta",
            "type": "Array<number>"
        },
        {
            "name": "networkConfig",
            "baseName": "networkConfig",
            "type": "string"
        },
        {
            "name": "supportedEntityVersions",
            "baseName": "supportedEntityVersions",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return NetworkConfigBodyDTO.attributeTypeMap;
    }
}

