/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class OfferInfoDTO {
    'mosaicId': Array<number>;
    'amount': Array<number>;
    'initialAmount': Array<number>;
    'initialCost': Array<number>;
    'deadline': Array<number>;
    'price': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mosaicId",
            "baseName": "mosaicId",
            "type": "Array<number>"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "Array<number>"
        },
        {
            "name": "initialAmount",
            "baseName": "initialAmount",
            "type": "Array<number>"
        },
        {
            "name": "initialCost",
            "baseName": "initialCost",
            "type": "Array<number>"
        },
        {
            "name": "deadline",
            "baseName": "deadline",
            "type": "Array<number>"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return OfferInfoDTO.attributeTypeMap;
    }
}

