/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { OfferDTO } from './offerDTO';
import { OfferTypeEnum } from './offerTypeEnum';

export class PrepareDriveTransactionBodyDTO extends OfferDTO {
    /**
    * The public key of the owner of the drive.
    */
    'owner': string;
    'duration': Array<number>;
    'billingPeriod': Array<number>;
    'billingPrice': Array<number>;
    'driveSize': Array<number>;
    'replicas': number;
    'minReplicators': number;
    'percentApprovers': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "owner",
            "baseName": "owner",
            "type": "string"
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "Array<number>"
        },
        {
            "name": "billingPeriod",
            "baseName": "billingPeriod",
            "type": "Array<number>"
        },
        {
            "name": "billingPrice",
            "baseName": "billingPrice",
            "type": "Array<number>"
        },
        {
            "name": "driveSize",
            "baseName": "driveSize",
            "type": "Array<number>"
        },
        {
            "name": "replicas",
            "baseName": "replicas",
            "type": "number"
        },
        {
            "name": "minReplicators",
            "baseName": "minReplicators",
            "type": "number"
        },
        {
            "name": "percentApprovers",
            "baseName": "percentApprovers",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(PrepareDriveTransactionBodyDTO.attributeTypeMap);
    }
}

