/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { ReceiptTypeEnum } from './receiptTypeEnum';

export class ReceiptDTO {
    /**
    * The version of the receipt.
    */
    'version': number;
    'type': ReceiptTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ReceiptTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return ReceiptDTO.attributeTypeMap;
    }
}

