/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { NamespaceTypeEnum } from './namespaceTypeEnum';

export class RegisterNamespaceTransactionBodyDTO {
    'namespaceType': NamespaceTypeEnum;
    'duration': Array<number>;
    'namespaceId': Array<number>;
    /**
    * The unique namespace name.
    */
    'name': string;
    'parentId': Array<number>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "namespaceType",
            "baseName": "namespaceType",
            "type": "NamespaceTypeEnum"
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "Array<number>"
        },
        {
            "name": "namespaceId",
            "baseName": "namespaceId",
            "type": "Array<number>"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "parentId",
            "baseName": "parentId",
            "type": "Array<number>"
        }    ];

    static getAttributeTypeMap() {
        return RegisterNamespaceTransactionBodyDTO.attributeTypeMap;
    }
}

