/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { HashAlgorithmEnum } from './hashAlgorithmEnum';

export class SecretLockTransactionBodyDTO {
    'duration': Array<number>;
    'mosaicId': Array<number>;
    'amount': Array<number>;
    'hashAlgorithm': HashAlgorithmEnum;
    /**
    * The proof hashed.
    */
    'secret': string;
    /**
    * The address in hexadecimal that will receive the funds once the transaction is unlocked.
    */
    'recipient': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "duration",
            "baseName": "duration",
            "type": "Array<number>"
        },
        {
            "name": "mosaicId",
            "baseName": "mosaicId",
            "type": "Array<number>"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "Array<number>"
        },
        {
            "name": "hashAlgorithm",
            "baseName": "hashAlgorithm",
            "type": "HashAlgorithmEnum"
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "string"
        },
        {
            "name": "recipient",
            "baseName": "recipient",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SecretLockTransactionBodyDTO.attributeTypeMap;
    }
}

