/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { MetaLockDTO } from './metaLockDTO';
import { SecretLockInfoDTO } from './secretLockInfoDTO';

export class SecretLockWithMeta {
    'meta': MetaLockDTO;
    'lock': SecretLockInfoDTO;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "meta",
            "baseName": "meta",
            "type": "MetaLockDTO"
        },
        {
            "name": "lock",
            "baseName": "lock",
            "type": "SecretLockInfoDTO"
        }    ];

    static getAttributeTypeMap() {
        return SecretLockWithMeta.attributeTypeMap;
    }
}

