/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { AccountLinkTransactionDTO } from './accountLinkTransactionDTO';
import { AccountPropertiesTransactionDTO } from './accountPropertiesTransactionDTO';
import { AddExchangeOfferTransactionDTO } from './addExchangeOfferTransactionDTO';
import { AddressAliasTransactionDTO } from './addressAliasTransactionDTO';
import { AddressMetadataTransactionDTO } from './addressMetadataTransactionDTO';
import { AggregateTransactionDTO } from './aggregateTransactionDTO';
import { BlockchainUpgradeTransactionDTO } from './blockchainUpgradeTransactionDTO';
import { DriveFileSystemTransactionDTO } from './driveFileSystemTransactionDTO';
import { DriveFilesRewardTransactionDTO } from './driveFilesRewardTransactionDTO';
import { EndDriveTransactionDTO } from './endDriveTransactionDTO';
import { EndDriveVerificationTransactionDTO } from './endDriveVerificationTransactionDTO';
import { ExchangeOfferTransactionDTO } from './exchangeOfferTransactionDTO';
import { FilesDepositTransactionDTO } from './filesDepositTransactionDTO';
import { HashLockTransactionDTO } from './hashLockTransactionDTO';
import { JoinToDriveTransactionDTO } from './joinToDriveTransactionDTO';
import { ModifyMultisigAccountTransactionDTO } from './modifyMultisigAccountTransactionDTO';
import { MosaicAliasTransactionDTO } from './mosaicAliasTransactionDTO';
import { MosaicDefinitionTransactionDTO } from './mosaicDefinitionTransactionDTO';
import { MosaicMetadataTransactionDTO } from './mosaicMetadataTransactionDTO';
import { MosaicSupplyChangeTransactionDTO } from './mosaicSupplyChangeTransactionDTO';
import { NamespaceMetadataTransactionDTO } from './namespaceMetadataTransactionDTO';
import { NetworkConfigTransactionDTO } from './networkConfigTransactionDTO';
import { PrepareDriveTransactionDTO } from './prepareDriveTransactionDTO';
import { RegisterNamespaceTransactionDTO } from './registerNamespaceTransactionDTO';
import { RemoveExchangeOfferTransactionDTO } from './removeExchangeOfferTransactionDTO';
import { SecretLockTransactionDTO } from './secretLockTransactionDTO';
import { SecretProofTransactionDTO } from './secretProofTransactionDTO';
import { StartDriveVerificationTransactionDTO } from './startDriveVerificationTransactionDTO';
import { TransactionMetaDTO } from './transactionMetaDTO';
import { TransferTransactionDTO } from './transferTransactionDTO';

export class TransactionInfoDTO {
    'meta': TransactionMetaDTO;
    'transaction': BlockchainUpgradeTransactionDTO | NetworkConfigTransactionDTO | AddressMetadataTransactionDTO | MosaicMetadataTransactionDTO | NamespaceMetadataTransactionDTO | MosaicDefinitionTransactionDTO | MosaicSupplyChangeTransactionDTO | RegisterNamespaceTransactionDTO | AddressAliasTransactionDTO | MosaicAliasTransactionDTO | TransferTransactionDTO | ModifyMultisigAccountTransactionDTO | AggregateTransactionDTO | HashLockTransactionDTO | AccountPropertiesTransactionDTO | SecretLockTransactionDTO | SecretProofTransactionDTO | AccountLinkTransactionDTO | AddExchangeOfferTransactionDTO | ExchangeOfferTransactionDTO | RemoveExchangeOfferTransactionDTO | PrepareDriveTransactionDTO | JoinToDriveTransactionDTO | DriveFileSystemTransactionDTO | FilesDepositTransactionDTO | EndDriveTransactionDTO | DriveFilesRewardTransactionDTO | StartDriveVerificationTransactionDTO | EndDriveVerificationTransactionDTO;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "meta",
            "baseName": "meta",
            "type": "TransactionMetaDTO"
        },
        {
            "name": "transaction",
            "baseName": "transaction",
            "type": "BlockchainUpgradeTransactionDTO | NetworkConfigTransactionDTO | AddressMetadataTransactionDTO | MosaicMetadataTransactionDTO | NamespaceMetadataTransactionDTO | MosaicDefinitionTransactionDTO | MosaicSupplyChangeTransactionDTO | RegisterNamespaceTransactionDTO | AddressAliasTransactionDTO | MosaicAliasTransactionDTO | TransferTransactionDTO | ModifyMultisigAccountTransactionDTO | AggregateTransactionDTO | HashLockTransactionDTO | AccountPropertiesTransactionDTO | SecretLockTransactionDTO | SecretProofTransactionDTO | AccountLinkTransactionDTO | AddExchangeOfferTransactionDTO | ExchangeOfferTransactionDTO | RemoveExchangeOfferTransactionDTO | PrepareDriveTransactionDTO | JoinToDriveTransactionDTO | DriveFileSystemTransactionDTO | FilesDepositTransactionDTO | EndDriveTransactionDTO | DriveFilesRewardTransactionDTO | StartDriveVerificationTransactionDTO | EndDriveVerificationTransactionDTO"
        }    ];

    static getAttributeTypeMap() {
        return TransactionInfoDTO.attributeTypeMap;
    }
}

