// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class RemoveSdaExchangeOfferBuffer {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): RemoveSdaExchangeOfferBuffer {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsRemoveSdaExchangeOfferBuffer(bb: flatbuffers.ByteBuffer, obj?: RemoveSdaExchangeOfferBuffer): RemoveSdaExchangeOfferBuffer {
    return (obj || new RemoveSdaExchangeOfferBuffer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsRemoveSdaExchangeOfferBuffer(bb: flatbuffers.ByteBuffer, obj?: RemoveSdaExchangeOfferBuffer): RemoveSdaExchangeOfferBuffer {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new RemoveSdaExchangeOfferBuffer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  mosaicIdGive(index: number): number | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.readUint32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
  }

  mosaicIdGiveLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  mosaicIdGiveArray(): Uint32Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? new Uint32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
  }

  mosaicIdGet(index: number): number | null {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset ? this.bb!.readUint32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
  }

  mosaicIdGetLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  mosaicIdGetArray(): Uint32Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset ? new Uint32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
  }

  static startRemoveSdaExchangeOfferBuffer(builder: flatbuffers.Builder) {
    builder.startObject(2);
  }

  static addMosaicIdGive(builder: flatbuffers.Builder, mosaicIdGiveOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, mosaicIdGiveOffset, 0);
  }

  static createMosaicIdGiveVector(builder: flatbuffers.Builder, data: number[] | Uint32Array): flatbuffers.Offset;
  /**
   * @deprecated This Uint8Array overload will be removed in the future.
   */
  static createMosaicIdGiveVector(builder: flatbuffers.Builder, data: number[] | Uint8Array): flatbuffers.Offset;
  static createMosaicIdGiveVector(builder: flatbuffers.Builder, data: number[] | Uint32Array | Uint8Array): flatbuffers.Offset {
    builder.startVector(4, data.length, 4);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addInt32(data[i]!);
    }
    return builder.endVector();
  }

  static startMosaicIdGiveVector(builder: flatbuffers.Builder, numElems: number) {
    builder.startVector(4, numElems, 4);
  }

  static addMosaicIdGet(builder: flatbuffers.Builder, mosaicIdGetOffset: flatbuffers.Offset) {
    builder.addFieldOffset(1, mosaicIdGetOffset, 0);
  }

  static createMosaicIdGetVector(builder: flatbuffers.Builder, data: number[] | Uint32Array): flatbuffers.Offset;
  /**
   * @deprecated This Uint8Array overload will be removed in the future.
   */
  static createMosaicIdGetVector(builder: flatbuffers.Builder, data: number[] | Uint8Array): flatbuffers.Offset;
  static createMosaicIdGetVector(builder: flatbuffers.Builder, data: number[] | Uint32Array | Uint8Array): flatbuffers.Offset {
    builder.startVector(4, data.length, 4);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addInt32(data[i]!);
    }
    return builder.endVector();
  }

  static startMosaicIdGetVector(builder: flatbuffers.Builder, numElems: number) {
    builder.startVector(4, numElems, 4);
  }

  static endRemoveSdaExchangeOfferBuffer(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static finishRemoveSdaExchangeOfferBufferBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset) {
    builder.finish(offset);
  }

  static finishSizePrefixedRemoveSdaExchangeOfferBufferBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset) {
    builder.finish(offset, undefined, true);
  }

  static createRemoveSdaExchangeOfferBuffer(builder: flatbuffers.Builder, mosaicIdGiveOffset: flatbuffers.Offset, mosaicIdGetOffset: flatbuffers.Offset): flatbuffers.Offset {
    RemoveSdaExchangeOfferBuffer.startRemoveSdaExchangeOfferBuffer(builder);
    RemoveSdaExchangeOfferBuffer.addMosaicIdGive(builder, mosaicIdGiveOffset);
    RemoveSdaExchangeOfferBuffer.addMosaicIdGet(builder, mosaicIdGetOffset);
    return RemoveSdaExchangeOfferBuffer.endRemoveSdaExchangeOfferBuffer(builder);
  }
}
