// Copyright 2019 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file

/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import http = require('http');
import axios from 'axios';
import {AxiosRequestConfig, AxiosResponse, AxiosError} from 'axios';

/* tslint:disable:no-unused-locals */
import { AddressMetadataInfoDTO } from '../model/addressMetadataInfoDTO';
import { MetadataIds } from '../model/metadataIds';
import { MetadataEntryGetInlineResponse } from '../model/metadataEntryGetInlineResponse'
import { MetadataEntriesDTO } from '../model/metadataEntriesDTO';
import { MetadataQueryParams } from '../metadataQueryParams';

import { ObjectSerializer } from '../model/models';

let defaultBasePath = 'http://localhost:3000';

export class MetadataRoutesApi {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    /**
     * Gets the metadata(AccountMetadataIndo, MosaicMetadataInfo or NamespaceMetadataInfo) for a given metadataId.
     * @summary Get metadata of namespace/mosaic/account
     * @param compositeHash The metadata compositeHash identifier.
     */
    public async getMetadata (compositeHash: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: AxiosResponse; body: MetadataEntryGetInlineResponse;  }> {
        const localVarPath = '/metadata_v2/{compositeHash}'
            .replace('{' + 'compositeHash' + '}', encodeURIComponent(String(compositeHash)));

        // verify required parameter 'compositeHash' is not null or undefined
        if (compositeHash === null || compositeHash === undefined) {
            throw new Error('Required parameter compositeHash was null or undefined when calling getMetadata.');
        }

        let localVarRequestOptions: AxiosRequestConfig = {
            method: 'GET',
            headers: { 
                'Content-Type': 'application/json', 
                'Accept': 'application/json'
            },
            url: localVarPath,
            baseURL: this.basePath,
            responseType: 'json'
        };

        return new Promise<{ response: AxiosResponse; body: MetadataEntryGetInlineResponse;  }>((resolve, reject) => {
            axios(localVarRequestOptions).then(
                (response)=>{
                    let body = ObjectSerializer.deserialize(response.data, "MetadataEntryGetInlineResponse");
                    if (response.status && response.status >= 200 && response.status <= 299) {
                        resolve({ response: response, body: body });
                    } else {
                            reject(response);
                    }
                },
                (error: AxiosError ) => {
                    reject(error);
                }
            );
        });
    }
    /**
     * Gets an array of metadata.
     * @summary Get metadatas(namespace/mosaic/account) for an array of compositeHashes
     * @param compositeHashes of metadata
     */
    public async getMetadatas (compositeHashes: string[], options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: AxiosResponse; body: Array<MetadataEntryGetInlineResponse>;  }> {
        const localVarPath = '/metadata_v2';

        let localVarRequestOptions: AxiosRequestConfig = {
            method: 'POST',
            headers: { 
                'Content-Type': 'application/json', 
                'Accept': 'application/json'
            },
            url: localVarPath,
            baseURL: this.basePath,
            responseType: 'json',
            data: ObjectSerializer.serialize(compositeHashes, "compositeHashes")
        };

        return new Promise<{ response: AxiosResponse; body: Array<MetadataEntryGetInlineResponse>;  }>((resolve, reject) => {
            axios(localVarRequestOptions).then(
                (response)=>{
                    let body = ObjectSerializer.deserialize(response.data, "Array<MetadataEntryGetInlineResponse>");
                    if (response.status && response.status >= 200 && response.status <= 299) {
                        resolve({ response: response, body: body });
                    } else {
                            reject(response);
                    }
                },
                (error: AxiosError ) => {
                    reject(error);
                }
            );
        });
    }
    /**
     * Gets the metadata for a given mosaicId.
     * @summary Search metadata
     * @param metadataQueryParams search filter
     */
    public async searchMetadata (metadataQueryParams?: MetadataQueryParams, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: AxiosResponse; body: MetadataEntriesDTO;  }> {
        const localVarPath = '/metadata_v2';

        let localVarQueryParameters: any = {};

        if(metadataQueryParams){
            localVarQueryParameters = metadataQueryParams.buildQueryParams();
        }

        let localVarRequestOptions: AxiosRequestConfig = {
            method: 'GET',
            headers: { 
                'Content-Type': 'application/json', 
                'Accept': 'application/json'
            },
            url: localVarPath,
            baseURL: this.basePath,
            responseType: 'json',
            params: localVarQueryParameters
        };

        return new Promise<{ response: AxiosResponse; body: MetadataEntriesDTO;  }>((resolve, reject) => {
            axios(localVarRequestOptions).then(
                (response)=>{
                    let body = ObjectSerializer.deserialize(response.data, "MetadataEntriesDTO");
                    if (response.status && response.status >= 200 && response.status <= 299) {
                        resolve({ response: response, body: body });
                    } else {
                            reject(response);
                    }
                },
                (error: AxiosError ) => {
                    reject(error);
                }
            );
        });
    }
}
